# Generated by Django 5.2.7 on 2025-10-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('preparacion', 'En Preparación'), ('listo', 'Listo para Servir'), ('entregado', 'Entregado')], default='recibido', max_length=20, verbose_name='Estado del Detalle'),
        ),
    ]
