# Generated by Django 5.2.7 on 2025-10-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_pedidodetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estacion',
            field=models.CharField(choices=[('cocina', 'Cocina'), ('bar', 'Bar/Mesero')], default='cocina', max_length=20, verbose_name='Estación de Preparación'),
        ),
    ]
