# Generated by Django 5.2.7 on 2025-10-19 23:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_categoria_estacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Fin')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10, verbose_name='Estado')),
                ('abierto_por', models.ForeignKey(limit_choices_to={'groups__name': 'Gerente'}, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por (Gerente)')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
